spring:
  application:
    name: fundraiser

  datasource:
    url: jdbc:mysql://localhost:3306/fund_raiser_details
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

  redis:
    host: localhost
    port: 6379

server:
  port: 9090
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET}

upload:
  dir: ${FILE_UPLOAD_DIR}

google:
  client-id: ${GOOGLE_CLIENT_ID}