spring:
  application:
    name: fundraiser

  datasource:
    url: jdbc:mysql://localhost:3306/fund_raiser_details
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 9090

jwt:
  secret: ${JWT_SECRET}

upload:
  dir: ${FILE_UPLOAD_DIR}